### ISSUE TITLE
Fails fo Building the MQTT and TLS libraries  under Windows 

### ISSUE THREAD

**Issue by WilliamFrasson** [xively/xively-client-c#153]
Hi All,
I got these messages try to complie  wolfssl  under windows 10 using msys shell:
"error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'"

here below the log
what i miss or did wrong?
thanks in advaced

--------------
```
$ make PRESET=ESP32

'# Using build PRESET: "ESP32" to set CONFIG and TARGET variables:
.    XI_BSP_PLATFORM: [esp32]
.    XI_BSP_TLS:      [wolfssl]

'# Xively C Client

. run 'make help' for more information, including a list of valid Build PRESETS.
.    CONFIG:          [memory_fs-tls_bsp]
.    TARGET:          [esp32-static-release]
.    COMPILER:        [xtensa-esp32-elf-gcc]

make[1]: ingresso nella directory "/c/esp32/xively-client-c/examples/esp32/xively_demo/wolfssl-make"
  [CC] /c/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c: In function 'wolfSSL_CertManagerFree':
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:2367:19: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
             if (cm->ocsp_stapling)
                   ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:2368:28: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
                 FreeOCSP(cm->ocsp_stapling, 1);
                            ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c: In function 'wolfSSL_CertManagerEnableOCSPStapling':
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:4793:15: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
         if (cm->ocsp_stapling == NULL) {
               ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:4794:15: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
             cm->ocsp_stapling = (WOLFSSL_OCSP*)XMALLOC(sizeof(WOLFSSL_OCSP),
               ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:4796:19: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
             if (cm->ocsp_stapling == NULL)
                   ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:4799:28: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
             if (InitOCSP(cm->ocsp_stapling, cm) != 0) {
                            ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:4801:28: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
                 FreeOCSP(cm->ocsp_stapling, 1);
                            ^
C:/esp32/xively-client-c/src/import/tls/wolfssl/src/ssl.c:4802:19: error: 'WOLFSSL_CERT_MANAGER {aka struct WOLFSSL_CERT_MANAGER}' has no member named 'ocsp_stapling'
                 cm->ocsp_stapling = NULL;
                   ^
make[1]: *** [Makefile:128: /c/esp32/xively-client-c/obj/esp32/wolfssl/src/ssl.o] Error 1
make[1]: uscita dalla directory "/c/esp32/xively-client-c/examples/esp32/xively_demo/wolfssl-make"
make: *** [make/mt-os/mt-esp32.mk:83: WOLFSSL_STATIC_LIB] Error 2
```
-------------------------------

**Comment by Palantir555** [comment]
Hi @WilliamFrasson, Thanks a lot for the report. Very glad to see users are already testing the new ESP32 port 

I've just tried building the library and example on windows, and I was able to do it without issues, so I'm not sure what's going on in your setup. These are the steps I followed:

1. Set up ESP-IDF as explained in steps 1, 2 and 4 in this document: https://esp-idf.readthedocs.io/en/v2.0/windows-setup.html
2. Clone `xively-client-c`
3. `cd xively-client-c && make PRESET=ESP32`

I got both static libraries (libxively.a and libwolfssl.a) without any errors.

Did you do anything differently? Any chance you're using a different WolfSSL version? (only possible if you downloaded it directly instead of letting the Makefiles do it).

If you've done everything the same way, and you're still running into the same error, you can try this:
Edit `xively-client-c/examples/esp32/xively_demo/wolfssl-make/Makefile` to remove the line `-DNO_WOLFSSL_SERVER \`, and try again. @atigyi Identified that macro as a likely root of the error; I can compile the library both with and without this flag, but it's worth a try.

Let us know if any of that helps, and whether you find out any new details.

Cheers!

**Comment by WilliamFrasson** [comment]
Hi Palantir555,
- i'm using esp-idf under folder "C:\esp32\esp-idf" but using the MASTER branch instead of branch "release 2.0" or 2.1; (master branch should be quite stable for many projects)
- I have cloned the "xively-client-c" under "C:\esp32\esp-idf\components" as ususal.

not i try to compile under idf "release 2.0" 
i will update you asap
thanks in advaced

**Comment by WilliamFrasson** [comment]
by removing  -DNO_WOLFSSL_SERVER   from wolfssl-make/Makefile i was able to compile.
now i have the two files:
libxively.a
libwolfssl.a

i will continue with the test now . I don't any idea of the impacts of removing   -DNO_WOLFSSL_SERVER

thz

**Comment by WilliamFrasson** [comment]
the app start. now the problem are more close to the demo:
- no way to detect button and send mqtt message to xively
- no way to set led via mqtt..

**Comment by WilliamFrasson** [comment]
resolved all

**Comment by atigyi** [comment]
Congrats William!!

The removal of NO_WOLFSSL_SERVER preprocessor definition activates code related to server side TLS handshake. This move makes libwolfssl.a little larger. I don't know the size increase though.

**Comment by atigyi** [comment]
v1.3.1 contains the fix
https://github.com/xively/xively-client-c/releases/tag/v1.3.1
